"""update model model_has_permission

Revision ID: 05c3cfeab74a
Revises: 9bdf7fa64e4d
Create Date: 2026-01-10 08:23:40.314770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05c3cfeab74a'
down_revision = '9bdf7fa64e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_has_permission', 'model_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_has_permission', sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    # ### end Alembic commands ###
