"""create unique name, semester and journey matier table

Revision ID: 05d73a10d594
Revises: 9d783243ca5f
Create Date: 2026-01-04 13:38:24.482856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d73a10d594'
down_revision = '9d783243ca5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_name_semester_journey', table_name='constituent_element')
    op.create_unique_constraint('uq_name_semester_journey_constituent_element', 'constituent_element', ['name', 'semester', 'id_journey'])
    op.create_unique_constraint('uq_name_semester_journey_teaching_unit', 'teaching_unit', ['name', 'semester', 'id_journey'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_semester_journey_teaching_unit', 'teaching_unit', type_='unique')
    op.drop_constraint('uq_name_semester_journey_constituent_element', 'constituent_element', type_='unique')
    op.create_index('uq_name_semester_journey', 'constituent_element', ['name', 'semester', 'id_journey'], unique=True)
    # ### end Alembic commands ###
