"""update table teaching unit offering

Revision ID: 0b12bdcf1de9
Revises: 3d7cf98cdc99
Create Date: 2026-01-02 16:56:50.568827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b12bdcf1de9'
down_revision = '3d7cf98cdc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_unit_offering', sa.Column('id_teaching_unit_optional_group', sa.Integer(), nullable=True))
    op.drop_constraint('teaching_unit_offering_ibfk_3', 'teaching_unit_offering', type_='foreignkey')
    op.create_foreign_key(None, 'teaching_unit_offering', 'teaching_unit_optional_group', ['id_teaching_unit_optional_group'], ['id'])
    op.drop_column('teaching_unit_offering', 'id_teaching_unit_goup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_unit_offering', sa.Column('id_teaching_unit_goup', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teaching_unit_offering', type_='foreignkey')
    op.create_foreign_key('teaching_unit_offering_ibfk_3', 'teaching_unit_offering', 'teaching_unit_optional_group', ['id_teaching_unit_goup'], ['id'])
    op.drop_column('teaching_unit_offering', 'id_teaching_unit_optional_group')
    # ### end Alembic commands ###
