"""add models model has permissions

Revision ID: 0edeee94cb05
Revises: 0f030dd4e0b7
Create Date: 2026-01-07 18:46:27.268519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0edeee94cb05'
down_revision = '0f030dd4e0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_has_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_permission', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('method_post', sa.Boolean(), nullable=True),
    sa.Column('method_get', sa.Boolean(), nullable=True),
    sa.Column('method_put', sa.Boolean(), nullable=True),
    sa.Column('method_delete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_has_permission_id'), 'model_has_permission', ['id'], unique=True)
    op.drop_column('permission', 'method_put')
    op.drop_column('permission', 'method_delete')
    op.drop_column('permission', 'method_get')
    op.drop_column('permission', 'method_post')
    op.drop_column('permission', 'model_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    op.add_column('permission', sa.Column('method_post', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('method_get', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('method_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('method_put', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_model_has_permission_id'), table_name='model_has_permission')
    op.drop_table('model_has_permission')
    # ### end Alembic commands ###
