"""update models notification templates add roles

Revision ID: 0f030dd4e0b7
Revises: 141268568d22
Create Date: 2026-01-07 06:23:24.292949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f030dd4e0b7'
down_revision = '141268568d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_template', sa.Column('target_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_template', 'target_roles')
    # ### end Alembic commands ###
