"""update table notification template add title

Revision ID: 141268568d22
Revises: c2945335f2cf
Create Date: 2026-01-06 19:00:28.373993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141268568d22'
down_revision = 'c2945335f2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_template', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_template', 'title')
    # ### end Alembic commands ###
