"""create table notification templates

Revision ID: 16a11447d225
Revises: 8535164bf646
Create Date: 2026-01-06 14:11:38.809162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a11447d225'
down_revision = '8535164bf646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_template_id'), 'notification_template', ['id'], unique=False)
    op.create_index(op.f('ix_notification_template_key'), 'notification_template', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_template_key'), table_name='notification_template')
    op.drop_index(op.f('ix_notification_template_id'), table_name='notification_template')
    op.drop_table('notification_template')
    # ### end Alembic commands ###
