"""drop id_anual_register

Revision ID: 1b5da1aac1de
Revises: afe13d980da4
Create Date: 2025-12-24 04:57:02.388452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b5da1aac1de'
down_revision = 'afe13d980da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annual_register_ibfk_2', 'annual_register', type_='foreignkey')
    op.drop_column('annual_register', 'id_enrollment_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_register', sa.Column('id_enrollment_fee', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('annual_register_ibfk_2', 'annual_register', 'enrollment_fee', ['id_enrollment_fee'], ['id'])
    # ### end Alembic commands ###
