"""add column name to model optional groupe 

Revision ID: 219371574aea
Revises: 9d770503b6ff
Create Date: 2026-01-05 05:05:32.697871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219371574aea'
down_revision = '9d770503b6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituent_element_optional_group', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('teaching_unit_optional_group', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_unit_optional_group', 'name')
    op.drop_column('constituent_element_optional_group', 'name')
    # ### end Alembic commands ###
