"""add model cms 

Revision ID: 2392c36948f8
Revises: a2eec571f214
Create Date: 2025-12-23 09:15:45.061959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2392c36948f8'
down_revision = 'a2eec571f214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_page_id'), 'cms_page', ['id'], unique=False)
    op.create_index(op.f('ix_cms_page_slug'), 'cms_page', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_page_slug'), table_name='cms_page')
    op.drop_index(op.f('ix_cms_page_id'), table_name='cms_page')
    op.drop_table('cms_page')
    # ### end Alembic commands ###
