"""update model available services

Revision ID: 2c3d7ea77d33
Revises: 5e7f9f9b9453
Create Date: 2025-12-23 15:19:17.846997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3d7ea77d33'
down_revision = '5e7f9f9b9453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_service', sa.Column('route_ui', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_service', 'route_ui')
    # ### end Alembic commands ###
