"""add unique user to tanle teacher

Revision ID: 3d7cf98cdc99
Revises: 44c9f0f8ef5a
Create Date: 2026-01-02 14:12:32.027585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7cf98cdc99'
down_revision = '44c9f0f8ef5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_for_teacher', 'teacher', ['id_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_for_teacher', 'teacher', type_='unique')
    # ### end Alembic commands ###
