"""update model document

Revision ID: 3eb1aaa8c884
Revises: 2c3d7ea77d33
Create Date: 2025-12-23 15:29:10.661206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb1aaa8c884'
down_revision = '2c3d7ea77d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('id_required_document', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'required_document', ['id_required_document'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'id_required_document')
    # ### end Alembic commands ###
