"""create table teached and update another table

Revision ID: 44c9f0f8ef5a
Revises: 4950abdee190
Create Date: 2026-01-02 11:56:32.131507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c9f0f8ef5a'
down_revision = '4950abdee190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Enum('MR', 'DR', 'PR', 'Mme', name='gradeenum'), nullable=True),
    sa.Column('max_hours_per_day', sa.Float(), nullable=True),
    sa.Column('max_days_per_week', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=True)
    op.add_column('constituent_element_offering', sa.Column('id_teacher', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constituent_element_offering', 'teacher', ['id_teacher'], ['id'])
    op.add_column('user', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('working_time', sa.Column('id_classroom', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'working_time', 'classroom', ['id_classroom'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_time', type_='foreignkey')
    op.drop_column('working_time', 'id_classroom')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'address')
    op.drop_constraint(None, 'constituent_element_offering', type_='foreignkey')
    op.drop_column('constituent_element_offering', 'id_teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    # ### end Alembic commands ###
