"""add foreing key num select annual register

Revision ID: 4950abdee190
Revises: f10aa7d55059
Create Date: 2026-01-01 06:22:54.888042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4950abdee190'
down_revision = 'f10aa7d55059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'annual_register', 'student', ['num_select'], ['num_select'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annual_register', type_='foreignkey')
    # ### end Alembic commands ###
