"""add column draft content

Revision ID: 5e7f9f9b9453
Revises: 2392c36948f8
Create Date: 2025-12-23 11:02:49.176399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7f9f9b9453'
down_revision = '2392c36948f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_page', sa.Column('draft_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_page', 'draft_content')
    # ### end Alembic commands ###
