"""add_unique_constraint_to_annual_register

Revision ID: 64ff9edd4b66
Revises: 2bfb9c425525
Create Date: 2025-12-22 09:57:33.428912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64ff9edd4b66'
down_revision = '2bfb9c425525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('student', 'enrollment_status',
               existing_type=mysql.ENUM('pending', 'selected', 'rejected', 'registered', 'former'),
               type_=sa.Enum('pending', 'rejected', 'selected', 'registered', 'former', name='enrollmentstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'enrollment_status',
               existing_type=sa.Enum('pending', 'rejected', 'selected', 'registered', 'former', name='enrollmentstatusenum'),
               type_=mysql.ENUM('pending', 'selected', 'rejected', 'registered', 'former'),
               existing_nullable=False)
    op.alter_column('payment', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
