"""update model enrollement fees

Revision ID: 683cbfb08d97
Revises: 3eb1aaa8c884
Create Date: 2025-12-23 17:37:12.642738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '683cbfb08d97'
down_revision = '3eb1aaa8c884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_fee', sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'M1', 'M2', name='levelenum'), nullable=False))
    op.drop_column('enrollment_fee', 'levels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_fee', sa.Column('levels', mysql.ENUM('PASSING', 'REPEATING', 'TRIPLING', charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False))
    op.drop_column('enrollment_fee', 'level')
    # ### end Alembic commands ###
