"""create table plugged

Revision ID: 73c5f15ea94c
Revises: 0b12bdcf1de9
Create Date: 2026-01-03 07:39:52.574768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73c5f15ea94c'
down_revision = '0b12bdcf1de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugged',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugged_id'), 'plugged', ['id'], unique=True)
    op.create_index(op.f('ix_plugged_name'), 'plugged', ['name'], unique=True)
    op.add_column('mention', sa.Column('id_plugged', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mention', 'plugged', ['id_plugged'], ['id'])
    op.drop_column('mention', 'plugged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mention', sa.Column('plugged', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    op.drop_constraint(None, 'mention', type_='foreignkey')
    op.drop_column('mention', 'id_plugged')
    op.drop_index(op.f('ix_plugged_name'), table_name='plugged')
    op.drop_index(op.f('ix_plugged_id'), table_name='plugged')
    op.drop_table('plugged')
    # ### end Alembic commands ###
