"""update model annual register

Revision ID: 7eaa1d3368e1
Revises: b5e3c76ae35f
Create Date: 2025-12-29 03:51:16.333851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaa1d3368e1'
down_revision = 'b5e3c76ae35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_register', sa.Column('num_select', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_annual_seletion_student_year', 'annual_register', ['num_select', 'id_academic_year', 'register_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_seletion_student_year', 'annual_register', type_='unique')
    op.drop_column('annual_register', 'num_select')
    # ### end Alembic commands ###
