"""add column verifed at and verified by

Revision ID: 7ebae7ce235d
Revises: 705ccc0da4ec
Create Date: 2025-12-22 12:43:29.284334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebae7ce235d'
down_revision = '705ccc0da4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_register', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('annual_register', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'annual_register', 'user', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annual_register', type_='foreignkey')
    op.drop_column('annual_register', 'verified_at')
    op.drop_column('annual_register', 'verified_by')
    # ### end Alembic commands ###
