"""add column description to model required documents

Revision ID: 84da14935e8f
Revises: eb44df1edab1
Create Date: 2025-12-23 04:22:57.918008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84da14935e8f'
down_revision = 'eb44df1edab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('required_document', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('required_document', 'description')
    # ### end Alembic commands ###
