"""update model working time

Revision ID: 8535164bf646
Revises: fe10cd4f3f17
Create Date: 2026-01-06 07:18:18.839694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8535164bf646'
down_revision = 'fe10cd4f3f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_time', sa.Column('id_teacher', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'working_time', 'teacher', ['id_teacher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_time', type_='foreignkey')
    op.drop_column('working_time', 'id_teacher')
    # ### end Alembic commands ###
