"""add column unique accademic year and session

Revision ID: 921713139fd8
Revises: 219371574aea
Create Date: 2026-01-05 11:35:53.339088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921713139fd8'
down_revision = '219371574aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_annual_register_session', 'exam_date', ['id_academic_year', 'session'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_register_session', 'exam_date', type_='unique')
    # ### end Alembic commands ###
