"""add_unique_constraint_to_annual_register

Revision ID: 96815d1c0734
Revises: 64ff9edd4b66
Create Date: 2025-12-22 10:14:29.322740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96815d1c0734'
down_revision = '64ff9edd4b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_annual_register_student_year', 'annual_register', ['num_carte', 'id_academic_year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_register_student_year', 'annual_register', type_='unique')
    # ### end Alembic commands ###
