"""update model model_has_permission

Revision ID: 9bdf7fa64e4d
Revises: a3ed24765028
Create Date: 2026-01-10 08:19:42.181506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf7fa64e4d'
down_revision = 'a3ed24765028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_has_permission', sa.Column('id_available_model', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model_has_permission', 'available_model', ['id_available_model'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_has_permission', type_='foreignkey')
    op.drop_column('model_has_permission', 'id_available_model')
    # ### end Alembic commands ###
