"""update model woring time

Revision ID: 9d770503b6ff
Revises: 05d73a10d594
Create Date: 2026-01-04 15:15:02.747957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d770503b6ff'
down_revision = '05d73a10d594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_time', sa.Column('id_constituent_element_offering', sa.Integer(), nullable=True))
    op.drop_constraint('working_time_ibfk_1', 'working_time', type_='foreignkey')
    op.create_foreign_key(None, 'working_time', 'constituent_element_offering', ['id_constituent_element_offering'], ['id'])
    op.drop_column('working_time', 'id_constituent_element')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_time', sa.Column('id_constituent_element', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'working_time', type_='foreignkey')
    op.create_foreign_key('working_time_ibfk_1', 'working_time', 'constituent_element_offering', ['id_constituent_element'], ['id'])
    op.drop_column('working_time', 'id_constituent_element_offering')
    # ### end Alembic commands ###
