"""create unique name, semester and journey

Revision ID: 9d783243ca5f
Revises: 73c5f15ea94c
Create Date: 2026-01-04 13:31:12.787332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d783243ca5f'
down_revision = '73c5f15ea94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_name_semester_journey', 'constituent_element', ['name', 'semester', 'id_journey'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_semester_journey', 'constituent_element', type_='unique')
    # ### end Alembic commands ###
