"""update models availables models

Revision ID: a2eec571f214
Revises: 8b7a5adf1d80
Create Date: 2025-12-23 07:47:49.573661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2eec571f214'
down_revision = '8b7a5adf1d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_model', sa.Column('route_api', sa.String(length=255), nullable=False))
    op.add_column('available_model', sa.Column('route_ui', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_model', 'route_ui')
    op.drop_column('available_model', 'route_api')
    # ### end Alembic commands ###
