"""update model model has permission, add column show from menu

Revision ID: a3ed24765028
Revises: 0edeee94cb05
Create Date: 2026-01-09 04:02:57.792422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ed24765028'
down_revision = '0edeee94cb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_has_permission', sa.Column('show_from_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_has_permission', 'show_from_menu')
    # ### end Alembic commands ###
