"""update model enrollement fees add unique contrainte

Revision ID: afe13d980da4
Revises: 683cbfb08d97
Create Date: 2025-12-24 04:02:00.592818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe13d980da4'
down_revision = '683cbfb08d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_annual_register_level_mention', 'enrollment_fee', ['level', 'id_academic_year', 'id_mention'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_register_level_mention', 'enrollment_fee', type_='unique')
    # ### end Alembic commands ###
