"""First migration

Revision ID: b12fcf3070b6
Revises: 
Create Date: 2025-11-15 18:57:11.785821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12fcf3070b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_year_id'), 'academic_year', ['id'], unique=True)
    op.create_index(op.f('ix_academic_year_name'), 'academic_year', ['name'], unique=True)
    op.create_table('baccalaureate_serie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_baccalaureate_serie_id'), 'baccalaureate_serie', ['id'], unique=True)
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_id'), 'classroom', ['id'], unique=True)
    op.create_table('feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_id'), 'feature', ['id'], unique=True)
    op.create_table('mention',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=255), nullable=False),
    sa.Column('plugged', sa.String(length=255), nullable=False),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mention_id'), 'mention', ['id'], unique=True)
    op.create_index(op.f('ix_mention_slug'), 'mention', ['slug'], unique=True)
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_id'), 'nationality', ['id'], unique=True)
    op.create_index(op.f('ix_nationality_name'), 'nationality', ['name'], unique=True)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=True)
    op.create_table('university',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('department_other_information', sa.String(length=255), nullable=True),
    sa.Column('department_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('logo_university', sa.String(length=255), nullable=True),
    sa.Column('logo_departement', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('admin_signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_email'), 'university', ['email'], unique=True)
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('enrollment_fee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('PASSING', 'REPEATING', 'TRIPLING', name='repeatstatusenum'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id_mention', sa.Integer(), nullable=True),
    sa.Column('id_academic_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_academic_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_mention'], ['mention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_fee_id'), 'enrollment_fee', ['id'], unique=True)
    op.create_table('exam_date',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_academic_year', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_academic_year'], ['academic_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_date_id'), 'exam_date', ['id'], unique=True)
    op.create_table('journey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=255), nullable=False),
    sa.Column('id_mention', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mention'], ['mention.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_journey_id'), 'journey', ['id'], unique=True)
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_permission', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=True)
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_carte', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('num_select', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=False),
    sa.Column('martial_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatusenum'), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('num_of_cin', sa.String(length=255), nullable=True),
    sa.Column('date_of_cin', sa.Date(), nullable=True),
    sa.Column('place_of_cin', sa.String(length=255), nullable=True),
    sa.Column('repeat_status', sa.Enum('PASSING', 'REPEATING', 'TRIPLING', name='repeatstatusenum'), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('num_of_baccalaureate', sa.String(length=255), nullable=False),
    sa.Column('center_of_baccalaureate', sa.String(length=255), nullable=False),
    sa.Column('year_of_baccalaureate', sa.Date(), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('father_job', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('mother_job', sa.String(length=255), nullable=True),
    sa.Column('parent_address', sa.Text(), nullable=True),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'M1', 'M2', name='levelenum'), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('enrollment_status', sa.Enum('pending', 'selected', 'rejected', 'registered', 'former', name='enrollmentstatusenum'), nullable=False),
    sa.Column('imported_id', sa.String(length=255), nullable=True),
    sa.Column('id_mention', sa.Integer(), nullable=True),
    sa.Column('id_enter_year', sa.Integer(), nullable=True),
    sa.Column('id_nationality', sa.Integer(), nullable=True),
    sa.Column('id_baccalaureate_series', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_baccalaureate_series'], ['baccalaureate_serie.id'], ),
    sa.ForeignKeyConstraint(['id_enter_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_mention'], ['mention.id'], ),
    sa.ForeignKeyConstraint(['id_nationality'], ['nationality.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_of_baccalaureate'),
    sa.UniqueConstraint('num_of_cin'),
    sa.UniqueConstraint('num_select')
    )
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=True)
    op.create_index(op.f('ix_student_num_carte'), 'student', ['num_carte'], unique=True)
    op.create_table('subscription_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subscription', sa.Integer(), nullable=True),
    sa.Column('id_feature', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_feature'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['id_subscription'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_feature_id'), 'subscription_feature', ['id'], unique=True)
    op.create_table('user_mention',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_mention', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mention'], ['mention.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mention_id'), 'user_mention', ['id'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=True)
    op.create_table('annual_register',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_carte', sa.String(length=255), nullable=True),
    sa.Column('id_academic_year', sa.Integer(), nullable=True),
    sa.Column('semester_count', sa.Integer(), nullable=False),
    sa.Column('id_enrollment_fee', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_academic_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_enrollment_fee'], ['enrollment_fee.id'], ),
    sa.ForeignKeyConstraint(['num_carte'], ['student.num_carte'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_register_id'), 'annual_register', ['id'], unique=True)
    op.create_table('constituent_element',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.String(length=255), nullable=True),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituent_element_id'), 'constituent_element', ['id'], unique=True)
    op.create_table('exam_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_classroom', sa.Integer(), nullable=True),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('num_from', sa.Integer(), nullable=False),
    sa.Column('num_to', sa.Integer(), nullable=False),
    sa.Column('session', sa.Enum('SN', 'SR', name='sessiontypeenum'), nullable=False),
    sa.Column('id_accademic_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_accademic_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_classroom'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_group_id'), 'exam_group', ['id'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=True)
    op.create_table('journey_semester',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_semester_id'), 'journey_semester', ['id'], unique=True)
    op.create_table('teaching_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_unit_id'), 'teaching_unit', ['id'], unique=True)
    op.create_table('teaching_unit_optional_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=True),
    sa.Column('selection_regle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_unit_optional_group_id'), 'teaching_unit_optional_group', ['id'], unique=True)
    op.create_table('payement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_annual_register', sa.Integer(), nullable=True),
    sa.Column('payed', sa.Float(), nullable=False),
    sa.Column('num_receipt', sa.String(length=255), nullable=False),
    sa.Column('date_receipt', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_annual_register'], ['annual_register.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_receipt')
    )
    op.create_index(op.f('ix_payement_id'), 'payement', ['id'], unique=True)
    op.create_table('register_semester',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_annual_register', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('repeat_status', sa.Enum('PASSING', 'REPEATING', 'TRIPLING', name='repeatstatusenum'), nullable=False),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('imported_id', sa.String(length=255), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_annual_register'], ['annual_register.id'], ),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_semester_id'), 'register_semester', ['id'], unique=True)
    op.create_table('student_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subscription', sa.Integer(), nullable=True),
    sa.Column('id_annual_register', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_annual_register'], ['annual_register.id'], ),
    sa.ForeignKeyConstraint(['id_subscription'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_subscription_id'), 'student_subscription', ['id'], unique=True)
    op.create_table('teaching_unit_offering',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_teaching_unit', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('id_academic_year', sa.Integer(), nullable=True),
    sa.Column('id_teaching_unit_goup', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_academic_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_teaching_unit'], ['teaching_unit.id'], ),
    sa.ForeignKeyConstraint(['id_teaching_unit_goup'], ['teaching_unit_optional_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_unit_offering_id'), 'teaching_unit_offering', ['id'], unique=True)
    op.create_table('constituent_element_optional_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_teaching_unit_offering', sa.Integer(), nullable=True),
    sa.Column('selection_regle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_teaching_unit_offering'], ['teaching_unit_offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituent_element_optional_group_id'), 'constituent_element_optional_group', ['id'], unique=True)
    op.create_table('result_teaching_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_register_semester', sa.Integer(), nullable=True),
    sa.Column('note', sa.Float(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_register_semester'], ['register_semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_teaching_unit_id'), 'result_teaching_unit', ['id'], unique=True)
    op.create_table('constituent_element_offering',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_constituent_element', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id_academic_year', sa.Integer(), nullable=True),
    sa.Column('id_constituent_element_optional_group', sa.Integer(), nullable=True),
    sa.Column('id_teching_unit_offering', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_academic_year'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['id_constituent_element'], ['constituent_element.id'], ),
    sa.ForeignKeyConstraint(['id_constituent_element_optional_group'], ['constituent_element_optional_group.id'], ),
    sa.ForeignKeyConstraint(['id_teching_unit_offering'], ['teaching_unit_offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituent_element_offering_id'), 'constituent_element_offering', ['id'], unique=True)
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_register_semester', sa.Integer(), nullable=True),
    sa.Column('id_constituent_element_offering', sa.Integer(), nullable=True),
    sa.Column('session', sa.Enum('SN', 'SR', name='sessiontypeenum'), nullable=False),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_constituent_element_offering'], ['constituent_element_offering.id'], ),
    sa.ForeignKeyConstraint(['id_register_semester'], ['register_semester.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_id'), 'note', ['id'], unique=True)
    op.create_table('working_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_constituent_element', sa.Integer(), nullable=True),
    sa.Column('working_time_type', sa.Enum('COURSE', 'TP', 'TD', 'EXAM', name='workingtimetypeenum'), nullable=False),
    sa.Column('day', sa.String(length=255), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('session', sa.Enum('SN', 'SR', name='sessiontypeenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_constituent_element'], ['constituent_element_offering.id'], ),
    sa.ForeignKeyConstraint(['id_group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_time_id'), 'working_time', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_time_id'), table_name='working_time')
    op.drop_table('working_time')
    op.drop_index(op.f('ix_note_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_constituent_element_offering_id'), table_name='constituent_element_offering')
    op.drop_table('constituent_element_offering')
    op.drop_index(op.f('ix_result_teaching_unit_id'), table_name='result_teaching_unit')
    op.drop_table('result_teaching_unit')
    op.drop_index(op.f('ix_constituent_element_optional_group_id'), table_name='constituent_element_optional_group')
    op.drop_table('constituent_element_optional_group')
    op.drop_index(op.f('ix_teaching_unit_offering_id'), table_name='teaching_unit_offering')
    op.drop_table('teaching_unit_offering')
    op.drop_index(op.f('ix_student_subscription_id'), table_name='student_subscription')
    op.drop_table('student_subscription')
    op.drop_index(op.f('ix_register_semester_id'), table_name='register_semester')
    op.drop_table('register_semester')
    op.drop_index(op.f('ix_payement_id'), table_name='payement')
    op.drop_table('payement')
    op.drop_index(op.f('ix_teaching_unit_optional_group_id'), table_name='teaching_unit_optional_group')
    op.drop_table('teaching_unit_optional_group')
    op.drop_index(op.f('ix_teaching_unit_id'), table_name='teaching_unit')
    op.drop_table('teaching_unit')
    op.drop_index(op.f('ix_journey_semester_id'), table_name='journey_semester')
    op.drop_table('journey_semester')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_exam_group_id'), table_name='exam_group')
    op.drop_table('exam_group')
    op.drop_index(op.f('ix_constituent_element_id'), table_name='constituent_element')
    op.drop_table('constituent_element')
    op.drop_index(op.f('ix_annual_register_id'), table_name='annual_register')
    op.drop_table('annual_register')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_mention_id'), table_name='user_mention')
    op.drop_table('user_mention')
    op.drop_index(op.f('ix_subscription_feature_id'), table_name='subscription_feature')
    op.drop_table('subscription_feature')
    op.drop_index(op.f('ix_student_num_carte'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_journey_id'), table_name='journey')
    op.drop_table('journey')
    op.drop_index(op.f('ix_exam_date_id'), table_name='exam_date')
    op.drop_table('exam_date')
    op.drop_index(op.f('ix_enrollment_fee_id'), table_name='enrollment_fee')
    op.drop_table('enrollment_fee')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_index(op.f('ix_university_email'), table_name='university')
    op.drop_table('university')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_nationality_name'), table_name='nationality')
    op.drop_index(op.f('ix_nationality_id'), table_name='nationality')
    op.drop_table('nationality')
    op.drop_index(op.f('ix_mention_slug'), table_name='mention')
    op.drop_index(op.f('ix_mention_id'), table_name='mention')
    op.drop_table('mention')
    op.drop_index(op.f('ix_feature_id'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_classroom_id'), table_name='classroom')
    op.drop_table('classroom')
    op.drop_index(op.f('ix_baccalaureate_serie_id'), table_name='baccalaureate_serie')
    op.drop_table('baccalaureate_serie')
    op.drop_index(op.f('ix_academic_year_name'), table_name='academic_year')
    op.drop_index(op.f('ix_academic_year_id'), table_name='academic_year')
    op.drop_table('academic_year')
    # ### end Alembic commands ###
