"""add register code in model annual register

Revision ID: b5e3c76ae35f
Revises: 1da335658d4c
Create Date: 2025-12-25 12:50:17.356536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e3c76ae35f'
down_revision = '1da335658d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_register', sa.Column('registration_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annual_register', 'registration_code')
    # ### end Alembic commands ###
