"""update table notification templates

Revision ID: c2945335f2cf
Revises: 16a11447d225
Create Date: 2026-01-06 14:28:01.143871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2945335f2cf'
down_revision = '16a11447d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_template', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notification_template', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notification_template', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_template', 'deleted_at')
    op.drop_column('notification_template', 'updated_at')
    op.drop_column('notification_template', 'created_at')
    # ### end Alembic commands ###
