"""update model role add use for card

Revision ID: de14ac8ae265
Revises: 20241110_0001
Create Date: 2025-12-20 13:53:14.978704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14ac8ae265'
down_revision = '20241110_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('use_for_card', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'use_for_card')
    # ### end Alembic commands ###
