"""create table for required document

Revision ID: eb44df1edab1
Revises: 7ebae7ce235d
Create Date: 2025-12-22 17:50:57.547181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb44df1edab1'
down_revision = '7ebae7ce235d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_service_id'), 'available_service', ['id'], unique=False)
    op.create_table('required_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_required_document_id'), 'required_document', ['id'], unique=False)
    op.create_table('available_service_required_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_available_service', sa.Integer(), nullable=True),
    sa.Column('id_required_document', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_available_service'], ['available_service.id'], ),
    sa.ForeignKeyConstraint(['id_required_document'], ['required_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_service_required_document_id'), 'available_service_required_document', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_available_service_required_document_id'), table_name='available_service_required_document')
    op.drop_table('available_service_required_document')
    op.drop_index(op.f('ix_required_document_id'), table_name='required_document')
    op.drop_table('required_document')
    op.drop_index(op.f('ix_available_service_id'), table_name='available_service')
    op.drop_table('available_service')
    # ### end Alembic commands ###
