"""create table card

Revision ID: ee53a3559c2c
Revises: b12fcf3070b6
Create Date: 2025-11-16 11:11:39.020535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee53a3559c2c'
down_revision = 'b12fcf3070b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('card_type', sa.Enum('STUDENT_CARD', 'USER_BADGE', name='cardtypeenum'), nullable=False),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('css_styles', sa.Text(), nullable=True),
    sa.Column('id_mention', sa.Integer(), nullable=True),
    sa.Column('id_journey', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_journey'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['id_mention'], ['mention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
