"""update model enrollment fees

Revision ID: f10aa7d55059
Revises: 7eaa1d3368e1
Create Date: 2025-12-30 04:18:55.235726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10aa7d55059'
down_revision = '7eaa1d3368e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_fee', sa.Column('register_type', sa.Enum('SELECTION', 'REGISTRATION', name='registertypeenum'), nullable=True))
    op.drop_index('uq_annual_register_level_mention', table_name='enrollment_fee')
    op.create_unique_constraint('uq_annual_renrollment_level_mention', 'enrollment_fee', ['level', 'id_academic_year', 'id_mention', 'register_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_renrollment_level_mention', 'enrollment_fee', type_='unique')
    op.create_index('uq_annual_register_level_mention', 'enrollment_fee', ['level', 'id_academic_year', 'id_mention'], unique=True)
    op.drop_column('enrollment_fee', 'register_type')
    # ### end Alembic commands ###
