"""update model group

Revision ID: fe10cd4f3f17
Revises: 921713139fd8
Create Date: 2026-01-05 14:40:49.173383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe10cd4f3f17'
down_revision = '921713139fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('id_academic_year', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('start_number', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('end_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'academic_year', ['id_academic_year'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'end_number')
    op.drop_column('group', 'start_number')
    op.drop_column('group', 'id_academic_year')
    # ### end Alembic commands ###
