"""updatemodel permissions

Revision ID: feefd35733f8
Revises: 84da14935e8f
Create Date: 2025-12-23 06:07:09.916946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feefd35733f8'
down_revision = '84da14935e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('method_post', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('method_get', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('method_put', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('method_delete', sa.Boolean(), nullable=True))
    op.drop_column('permission', 'method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('method', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('permission', 'method_delete')
    op.drop_column('permission', 'method_put')
    op.drop_column('permission', 'method_get')
    op.drop_column('permission', 'method_post')
    # ### end Alembic commands ###
