from .crud_enrollment_fee import enrollment_fee
from .crud_user_mention import user_mention
from .crud_mention import mention
from .crud_teaching_unit_offering import teaching_unit_offering
from .crud_university import university
from .crud_exam_group import exam_group
from .crud_student import student
from .crud_permission import permission
from .crud_academic_year import academic_year
from .crud_subscription_feature import subscription_feature
from .crud_note import note
from .crud_student_subscription import student_subscription
from .crud_exam_date import exam_date
from .crud_subscription import subscription
from .crud_teaching_unit_optional_group import teaching_unit_optional_group
from .crud_teaching_unit import teaching_unit
from .crud_register_semester import register_semester
from .crud_nationality import nationality
from .crud_constituent_element_offering import constituent_element_offering
from .crud_journey import journey
from .crud_result_teaching_unit import result_teaching_unit
from .crud_document import document
from .crud_user_role import user_role
from .crud_constituent_element import constituent_element
from .crud_constituent_element_optional_group import constituent_element_optional_group
from .crud_feature import feature
from .crud_role_permission import role_permission
from .crud_payment import payment
from .crud_user import user
from .crud_group import group
from .crud_classroom import classroom
from .crud_journey_semester import journey_semester
from .crud_role import role
from .crud_annual_register import annual_register
from .crud_working_time import working_time
from .crud_baccalaureate_serie import baccalaureate_serie
from .crud_card_asset import card_asset
from .crud_file_asset import file_asset
