# Import all the models, so that Base has them before being
# imported by Alembic
from app.db.base_class import Base # noqa
from app.models.student import Student # noqa
from app.models.mention import Mention # noqa
from app.models.journey import Journey # noqa
from app.models.document import Document # noqa
from app.models.academic_year import AcademicYear # noqa
from app.models.register_semester import RegisterSemester # noqa
from app.models.annual_register import AnnualRegister # noqa
from app.models.enrollment_fee import EnrollmentFee # noqa
from app.models.journey_semester import JourneySemester # noqa
from app.models.nationality import Nationality # noqa
from app.models.group import Group # noqa
from app.models.role import Role # noqa
from app.models.user import User # noqa
from app.models.user_role import UserRole # noqa
from app.models.university import University # noqa
from app.models.permission import Permission # noqa
from app.models.role_permission import RolePermission # noqa
from app.models.classroom import Classroom # noqa
from app.models.teaching_unit import TeachingUnit # noqa
from app.models.teaching_unit_optional_group import TeachingUnitOptionalGroup # noqa
from app.models.constituent_element import ConstituentElement # noqa
from app.models.constituent_element_optional_group import ConstituentElementOptionalGroup # noqa
from app.models.user_mention import UserMention # noqa
from app.models.subscription import Subscription # noqa
from app.models.feature import Feature # noqa
from app.models.subscription_feature import SubscriptionFeature # noqa
from app.models.student_subscription import StudentSubscription # noqa
from app.models.working_time import WorkingTime # noqa
from app.models.baccalaureate_serie import BaccalaureateSerie # noqa
from app.models.exam_date import ExamDate # noqa
from app.models.exam_group import ExamGroup # noqa
from app.models.note import Note # noqa
from app.models.result_teaching_unit import ResultTeachingUnit # noqa
from app.models.constituent_element_offering import ConstituentElementOffering # noqa
from app.models.teaching_unit_offering import TeachingUnitOffering # noqa
from app.models.payment import Payment # noqa
from app.models.file_asset import FileAsset # noqa
from app.models.required_document import RequiredDocument # noqa
from app.models.available_service import AvailableService # noqa
from app.models.available_model import AvailableModel # noqa
from app.models.service_required_document import AvailableServiceRequiredDocument # noqa
